### ISSUE TITLE
Invalid syntax of the example yaml file in README.md (`You have an error in your yaml syntax on line 23`)

### ISSUE THREAD

**Issue by WangYihang** [lvignoli/typst-action#13]
## Description

As the figure shows.

![image](https://github.com/user-attachments/assets/45003315-4ccc-4867-8423-a0c5df85f254)

## Solution

```yaml
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: *.pdf
```

should be

```yaml
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: "*.pdf"
```
