### ISSUE TITLE
Feature Request: Allow Users to Specify Custom Font Folder

### ISSUE THREAD

**Issue by DeveloperPaul123** [lvignoli/typst-action#5]
Typst supports custom font directories with the `--font-dir` argument. See [this](https://github.com/typst/typst#usage) section of the documentation. It would be nice to allow users to specify a directory as part of the CI.

One option: 

```yaml

- name: Typst
  uses: lvignoli/typst-action@b2161f52657ae108c74b1ceaf20e5fd4024d77de
  with:
    source_file: |
      resume.typ
    font-dir: ".../fonts"
```
