### ISSUE TITLE
Cannot specify --font-path

### ISSUE THREAD

**Issue by msakuta** [lvignoli/typst-action#9]
Hi, it seems this example action in the description [here](https://github.com/lvignoli/typst-action/blob/f8bb08eb807d02565f31f9684d141f4a02be3cb7/action.yml#L24) doesn't work.

```
      with:
        source_file: euler-lagrange-jp.typ
        - name: Typst
          uses: lvignoli/typst-action@main
          with:
            source_file: main.typ
            options: |
              --font-path
              fonts
```

In [my pipeline](https://github.com/msakuta/typst-test/actions/runs/6065442302/job/16454943700#step:5:8), the actual command executed seems like this (omitting irrelevant parameters to docker)

```
7   docker <blah..blah...> "euler-lagrange-jp.typ" "--font-path
8   fonts
9   "
```

which suggests that it's supposed to be like below, but the newline separated parameters actually go to the next command.

```
7   docker <blah..blah...> "euler-lagrange-jp.typ" "--font-path" "fonts"
```

**Comment by lvignoli** [comment]
Hi @msakuta,
The action is out of date with the current typst CLI.
I need to take some time to update, but this will not happen in the coming weeks.
In the meantime, I suggest you try [setup-typst](https://github.com/yusancky/setup-typst) as a replacement :)

**Comment by leana8959** [comment]
Hello,

I just opened a PR, I basically just swapped the option so that options comes _after_ the "compile filename.typ" part.

Hope this helps!

**Comment by Lypsilonx** [comment]
You can specify the environment variable like this:

```
- name: Typst
        uses: lvignoli/typst-action@main
        env:
          TYPST_FONT_PATHS: ./fonts
        with:
          source_file: |
             ...
```
